### ISSUE TITLE
Lemmas MUST have sameword annotation

### ISSUE THREAD

**Issue by stenskjaer** [stenskjaer/samewords#24]
This is a general bug covering **ALL** annotations.

Based on #23 and #13 it is clear that all `\lemma{}` macros need the `\sameword{}` annotation too.

**Comment by stenskjaer** [comment]
This was fun! Really had to make some considerable changes to solve my own blunder here. 

Thank you @floriandk for noticing the problems with the missing lemma annotation. Can you maybe help me confirm that now the `\lemma{}` is correctly annotated in a test case like for example the hyphens example from the other issues.

The branch is [issue-24](https://github.com/stenskjaer/samewords/tree/issue-24).

An example file could look like this:
```tex
\documentclass{article}

\usepackage[series={A},nofamiliar,noeledsec,noledgroup,draft]{reledmac}

\begin{document}

\beginnumbering
\pstart
\edtext{B}{\Afootnote{del.}}
\edtext{F}{\Afootnote{del.}}
\edtext{B C D E F}{\lemma{B--F}\Afootnote{b c d e f}}
\edtext{B}{\Afootnote{bb}}
\edtext{F}{\Afootnote{ff}}
\pend
\endnumbering

\end{document}
```

**Comment by floriandk** [comment]
This is looking good!
Basic funcionallity and also some complex nesting work as expected.

Until now I've only found one combination that doesn't work and this is a quite peculiar one which I am not even sure occurs in real life. But anyway;  might be it shows you something interesting :

```latex
\documentclass[a5paper]{scrartcl}

\usepackage[series={A},nofamiliar,noeledsec,noledgroup,draft]{reledmac}

\begin{document}

\beginnumbering
\pstart
\edtext{B}{%
	\Afootnote{b}}
%
\edtext{F %this space is crucial
}{%
	\lemma{F--B}%
	\Afootnote{del.}}
\pend
\endnumbering

\end{document}
```

is aborted with 

```python
Traceback (most recent call last):
  File "/usr/local/bin/samewords", line 11, in <module>
    load_entry_point('samewords', 'console_scripts', 'samewords')()
  File "~/samewords-issue-24/samewords/cli.py", line 99, in main
    output_content = samewords.core.process_document(filename)
  File "~/samewords-issue-24/samewords/core.py", line 26, in process_document
    chunk = ''.join([run_annotation(par) for par in chunk_pars(chunk)])
  File "~/samewords-issue-24/samewords/core.py", line 26, in <listcomp>
    chunk = ''.join([run_annotation(par) for par in chunk_pars(chunk)])
  File "~/samewords-issue-24/samewords/core.py", line 12, in run_annotation
    words = matcher.annotate()
  File "~/samewords-issue-24/samewords/matcher.py", line 50, in annotate
    self._add_sameword(edtext[-1:], edtext_lvl)
  File "~/samewords-issue-24/samewords/matcher.py", line 200, in _add_sameword
    word.add_macro(sw_macro)
  File "~/samewords-issue-24/samewords/tokenize.py", line 207, in add_macro
    pos = positions[0]
IndexError: list index out of range
```

afaics it only happens when there is a "wrong" `\lemma` and a space inside `\edtext` -- either of which might occur under specific circumstances, but I can hardly image a real-life scenario with both.

Perhaps you could just catch occurences of `\lemma` that don't include words from the `\edtext` and let the script include some warning like "`% non-standard usage of \lemma, not processed by samewords`"?

**Comment by stenskjaer** [comment]
This was actually not as particular as you suggest. The problem applies to all cases where the first or last word of the `\lemma{}` is not the first or last word (after tokenization) in the `\edtext{}` element. 

Examples:
```latex
B \edtext{F and some B %
}{\lemma{F--B}} % the B gives problems
F \edtext{ % 
```

```latex
F \edtext{ % 
F and B}{\lemma{F--B}} % The F gives problems
```

```latex
B F \edtext{ % 
F and B%
}{\lemma{F--B}} % Both F and B give problems
```

So, I have pushed some changes to branch "issue-24". 
In my tests I get the following results:

*Not last index* 
```latex
\documentclass[a5paper]{scrartcl}

\usepackage[series={A},nofamiliar,noeledsec,noledgroup,draft]{reledmac}

\begin{document}

\beginnumbering
\pstart
B \edtext{F and some B %
}{\lemma{F--B}}
\pend
\endnumbering

\end{document}
```
Gives
```latex
\documentclass[a5paper]{scrartcl}

\usepackage[series={A},nofamiliar,noeledsec,noledgroup,draft]{reledmac}

\begin{document}

\beginnumbering
\pstart
\sameword{B} \edtext{F and some \sameword[1]{B %
}}{\lemma{F--\sameword{B}}}
\pend
\endnumbering

\end{document}
```

*Not first index*
```latex
\documentclass[a5paper]{scrartcl}

\usepackage[series={A},nofamiliar,noeledsec,noledgroup,draft]{reledmac}

\begin{document}

\beginnumbering
\pstart
F \edtext{ % 
F and B}{\lemma{F--B}}
\pend
\endnumbering

\end{document}
```
Gives
```latex
\documentclass[a5paper]{scrartcl}

\usepackage[series={A},nofamiliar,noeledsec,noledgroup,draft]{reledmac}

\begin{document}

\beginnumbering
\pstart
\sameword{F} \edtext{\sameword[1]{ % 
F} and B}{\lemma{\sameword{F}--B}}
\pend
\endnumbering

\end{document}
```

*Neither first nor last index*
```latex
\documentclass[a5paper]{scrartcl}

\usepackage[series={A},nofamiliar,noeledsec,noledgroup,draft]{reledmac}

\begin{document}

\beginnumbering
\pstart
B F \edtext{ % 
F and B %
}{\lemma{F--B}}
\pend
\endnumbering

\end{document}
```
Gives
```latex
\documentclass[a5paper]{scrartcl}

\usepackage[series={A},nofamiliar,noeledsec,noledgroup,draft]{reledmac}

\begin{document}

\beginnumbering
\pstart
\sameword{B} \sameword{F} \edtext{\sameword[1]{ % 
F} and \sameword[1]{B %
}}{\lemma{\sameword{F}--\sameword{B}}}
\pend
\endnumbering

\end{document}
```

Are your results similar on that branch?

**Comment by floriandk** [comment]
Thinking about it, I can now imagine quite a number of real-world scenarios anyway:
Some editors don't necessarily want to replicate the word from the text exactly in the apparatus, e.g. adding or leaving out editorial marks like parenthesis.
Another one might be when the apparatus-code has to be disattached from the its actual place in the text, eg. when nesting is impossible because of overlapping structures.

And then there will be just plain mistakes when putting brackets in place...

So -- really good that you address this!

I can reproduce your results here and there no more break-offs when there is a mismatch between `edtext` and `lemma`. Good :)

I am not entirely sure though, whether the result is the  one we need...

When you TeX 

```latex
\documentclass[a5paper]{scrartcl}

\usepackage[series={A},nofamiliar,noeledsec,noledgroup,draft]{reledmac}

\begin{document}

\beginnumbering
\pstart
\sameword{F} \edtext{\sameword[1]{ % 
F} and B}{\lemma{\sameword{F}--B}\Afootnote{test}}
\pend
\endnumbering

\end{document}
```

the apparatus obviously becomes: "1 F–B] test" without the numbering of the "F". My immediate expectation would be that it should be: "1 F²–B] test" and thus

```latex
\documentclass[a5paper]{scrartcl}

\usepackage[series={A},nofamiliar,noeledsec,noledgroup,draft]{reledmac}

\begin{document}

\beginnumbering
\pstart
\sameword{F} \edtext{ % 
\sameword[1]{F} and B}{\lemma{\sameword{F}--B}\Afootnote{test}}
\pend
\endnumbering

\end{document}
```

Personally I'd be very happy if `samewords` would provide this solution.

(On the other hand you could argue that the inclusion of the starting space into `edtext` is a mistake and that it is not the script's job to "fix" these.)

**Comment by floriandk** [comment]
If the extra space occurs both in the `edtext` and the `lemma` e.g.

```latex
\documentclass[a5paper]{scrartcl}

\usepackage[series={A},nofamiliar,noeledsec,noledgroup,draft]{reledmac}

\begin{document}

\beginnumbering
\pstart
F \edtext{ F and B}{\lemma{ F--B}\Afootnote{test}}
\pend
\endnumbering

\end{document}
```

 the script still hangs:

```python
Traceback (most recent call last):
  File "/usr/local/bin/samewords", line 11, in <module>
    load_entry_point('samewords', 'console_scripts', 'samewords')()
  File "samewords-test/samewords-issue-24/samewords/cli.py", line 99, in main
    output_content = samewords.core.process_document(filename)
  File "samewords-test/samewords-issue-24/samewords/core.py", line 26, in process_document
    chunk = ''.join([run_annotation(par) for par in chunk_pars(chunk)])
  File "samewords-test/samewords-issue-24/samewords/core.py", line 26, in <listcomp>
    chunk = ''.join([run_annotation(par) for par in chunk_pars(chunk)])
  File "samewords-test/samewords-issue-24/samewords/core.py", line 12, in run_annotation
    words = matcher.annotate()
  File "samewords-test/samewords-issue-24/samewords/matcher.py", line 50, in annotate
    self._add_sameword(edtext[:sidx], edtext_lvl)
  File "samewords-test/samewords-issue-24/samewords/matcher.py", line 205, in _add_sameword
    part[-1].append_suffix('}')
  File "samewords-test/samewords-issue-24/samewords/tokenize.py", line 240, in append_suffix
    'Word: {}'.format(self.full())
ValueError: The correct position for the suffix could not be determinedWord: \edtext{\sameword[1]{ 
```

**Comment by floriandk** [comment]
Other divergence from the actual `edtext` are still problematic:

```latex
\documentclass[a5paper]{scrartcl}

\usepackage[series={A},nofamiliar,noeledsec,noledgroup,draft]{reledmac}

\begin{document}

\beginnumbering
\pstart
B, F, B and FF and \edtext{(F and B)}{\lemma{F--B}\Afootnote{test}}
\pend
\endnumbering

\end{document}
```

gives:

```latex 
\documentclass[a5paper]{scrartcl}

\usepackage[series={A},nofamiliar,noeledsec,noledgroup,draft]{reledmac}

\begin{document}

\beginnumbering
\pstart
\sameword{B}, \sameword{F}, \sameword{B} and FF and \edtext{(\sameword[1]{F} and \sameword[1]{B)}}{\lemma{\sameword{F}--\sameword{B}}\Afootnote{test}}
\pend
\endnumbering

\end{document}
```

resulting in "1 F²–B¹ ] test"

Other possible editorial marks like `{F and B}`, `[F and B]` or more less general ones like `⸠F and B⸡`, `⸍F and B⸌` or

```latex
\documentclass[a5paper]{scrartcl}

\usepackage{fontspec}
\setromanfont{Junicode}

\usepackage[series={A},nofamiliar,noeledsec,noledgroup,draft]{reledmac}

\begin{document}


\beginnumbering
\pstart
B, F, B and FF and \edtext{⟨F and B⟩}{\lemma{F--B}\Afootnote{test}}
\pend
\endnumbering

\end{document}
```

produce non-compiling results:

```latex 
\documentclass[a5paper]{scrartcl}

\usepackage{fontspec}
\setromanfont{Junicode}

\usepackage[series={A},nofamiliar,noeledsec,noledgroup,draft]{reledmac}

\begin{document}


\beginnumbering
\pstart
\sameword{B}, \sameword{F}, \sameword{B} and FF and \edtext{\sameword[1]{\sameword[1]{⟨F} and B⟩}}{\lemma{\sameword{F}--\sameword{B}}\Afootnote{test}}
\pend
\endnumbering

\end{document}
```

**Comment by stenskjaer** [comment]
Damn, I see. Of course. I'm not it.

About the selective (or moved) annotations such as this:
```latex
\sameword{F} \edtext{ % 
\sameword[1]{F} and B}{\lemma{\sameword{F}--B}\Afootnote{test}}
```
There wouldn't be any problems with that sort of stuff as long as we just make sure that the annotation wraps the first and last *word* (understood as one or more `\w` characters, possibly wrapped in one or more macros), right? I mean in terms of how the sameword counting comes out.
It shouldn't be too difficult to make it work like that.

The part about the parenthesis and other marks is maybe a bit more hairy. But I'll let you know.

**Comment by floriandk** [comment]
> There wouldn't be any problems with that sort of stuff as long as we just make sure that the annotation wraps the first and last word (understood as one or more \w characters, possibly wrapped in one or more macros), right? I mean in terms of how the sameword counting comes out.

If I understand you correctly, I think that's correct ;)

**Comment by stenskjaer** [comment]
Right now I have the following characters registered as punctuation:
```python
(
    r'['    # open
    r'!"#$&\'()*+,-./:;<=>?@^_`|~–—\[\]'    # general punctuation
    r'⟦⟧⟨⟩⟪⟫⟬⟭⟮⟯'       # special brackets from the Misc Mat. Symbols A   
    r'\u2000-\u206F'    # General punctuation (≠ the punctuation above)      
    r'\u2e00-\u2e7f'    # Supplemental punctuation
    r']+'   # close
)
```
I have added a configuration option (`punctuation`) which makes it possible to add custom punctuation characters or code ranges.

This means that 
```
B˧ \edtext{B}{}
```
Is annotated as
```
\sameword{B}˧ \edtext{\sameword[1]{B}}{}
```

In my tests it also solves the problems that you have pointed out. Thus (I've inserted linebreaks for readibility):
```
B, F, \edtext{⟨F and B⟩}{\lemma{F--B}\Afootnote{test}}
```
becomes
```
\sameword{B}, \sameword{F} \edtext{(\sameword[1]{F} and \sameword[1]
{B})}{\lemma{\sameword{F}--\sameword{B}}\Afootnote{test}}
```

```
o “o ⸀o o. o \edtext{o}{}
```
(from #25) becomes
```
\sameword{o} “\sameword{o} ⸀\sameword{o} \sameword{o}.
\sameword{o} \edtext{\sameword[1]{o}}{}
```

```
B, F, \edtext{⟨F and B⟩}{\lemma{F--B}\Afootnote{test}}
```
becomes
```
\sameword{B}, \sameword{F}, \edtext{⟨\sameword[1]{F} and 
\sameword[1]{B}⟩}{\lemma{\sameword{F}--\sameword{B}}
\Afootnote{test}}
```

And finally there is the `{}` and `[]` brackets. Of course you can't just use them as such in LaTeX. So one possibility is to bracket them as e.g. `{{}` and `{}}`. If that it done it works as expected:
```
'B, F, \edtext{{{}F and B{}}}{\lemma{F--B}\Afootnote{test}}'
```
becomes
```
\sameword{B}, \sameword{F}, \edtext{{{}\sameword[1]{F} and 
\sameword[1]{B}{}}}{\lemma{\sameword{F}--\sameword{B}}
\Afootnote{test}}
```

I would not personally recommend this way of making such editiorial marks (especially not the last one) but rather strongly recommend using custom macros, for instance a `\supplied{}` or whatever to annotate all such things (that makes later editing the style *much* easier). But that also works:
```
B, F, \edtext{\supplied{F} and B}{\lemma{F--B}}
```
becomes
```
\sameword{B}, \sameword{F}, \edtext{\supplied{\sameword[1]{F}} and \sameword[1]
{B}}{\lemma{\sameword{F}--\sameword{B}}}
```

I have pushed this stuff to "branch-24" and also added some notes to the readme.

**Comment by stenskjaer** [comment]
I think I'm going to merge and close this now.

**Comment by floriandk** [comment]
Just tried out the punctuation configuration -- this is working nicely!
I'd just suggest to add «» (00AB and 00BB) and perhaps 00BF and 00A1 to the standard list which for historical reasons stand on their own in Latin1 Supplement.

**Comment by stenskjaer** [comment]
Good point. They are added in the next minor update (when the space issue you raised is solved).
